### ISSUE TITLE
check modifies ndarray unbeknownst to caller

### ISSUE THREAD

**Issue by gadamc** [AdamPallus/artmagic#3]
You should check if this is true, but I think that when somebody calls this function, their input numpy array is modified and that would be unexpected.  For example 

```
pred=model.predict(img)
matches=find_matches(pred, collection_features, files_and_titles['imgfile'],dist='cosine')

#your pred numpy array has now been flattened. NEED TO CHECK THIS IS TRUE
```

**Looking at the rest of this function, you can just remove this line entirely.** 

https://github.com/AdamPallus/artmagic/blob/db0352391c0a108173c6248a274e766c1576e70c/artmagic/models/similarity.py#L30

**Comment by AdamPallus** [comment]
Luckily, pred needs to be flattened and is used only once. When I revise this code, I will flatten before saving the data to skip this step.
